### PR TITLE
Fix DEREE Judge project using BDD and Codeception testing framework. …

### LINKED ISSUE #17: Wrong title for DEREE Judge - Sample of Work
When hovering over the DEREE Judge project in the sample of work section, it displays the wrong name.

### PR DESCRIPTION
**Pull request by rdok**
This should close #17 
I am also setting  up a integration server for the tests in the near future. 

[Here](https://github.com/rdok/company-web-app/blob/master/tests/acceptance/sample-work.feature)  is the business expectation in relations to this issue. 

If you wish to run the tests:
1. Create a local web server, pointing to codeburrow.app
2. Download http://www.seleniumhq.org/download/, and execute it

```
$ java -jar selenium-server-standalone-3.0.0-beta3.jar 
```
1. Execute the tests

```
$ ./vendor/bin/codecept run
```

All the above steps will be automatically run from the integration servers when I set it up. 

@PadawanTony 
@NourhanElshenawi

### CODE REVIEW

**Comment by PadawanTony** [comment]
@rdok I already have a `codeburrow.app` in homestead.

Are you done with this issue? Should I review it and merge?

**Comment by rdok** [comment]
@PadawanTony Yes please. You'll notice, only one file/line has been changed for the actual production code. All the rest are just jargon for the tests. Which means the deployment does not require anything but just pull the code.

**Comment by PadawanTony** [comment]
@rdok I managed to download and install everything (so many modules were missing from my php7 installation) 

1) When I run the first cmd (`java -jar selenium-server-standalone-3.0.0-beta3.jar`) the terminal remains open (I mean the cmd is running) until I press ctl + X. Is this the required behaviour?

2) When I run the 2nd cmd (`./vendor/bin/codecept run`) a new chrome window opens (I guess it it testing) and then closes. Is this the required behaviour? Here is a screenshot:
image

3) Here are the results I get. Is this the required behaviour?

``` bash
antony:~/Code/company-web-app$ ./vendor/bin/codecept run
Codeception PHP Testing Framework v2.2.4
Powered by PHPUnit 5.4.8 by Sebastian Bergmann and contributors.

Acceptance Tests (1) --------------------------------------------------------
✔ sample-work: see DEREE Judge name and screenshot (19.65s)
-----------------------------------------------------------------------------


Time: 21.11 seconds, Memory: 10.00MB

OK (1 test, 4 assertions)
```

**Comment by rdok** [comment]
@PadawanTony Nice work setting it up and all! 

> 1) When I run the first cmd (java -jar selenium-server-standalone-3.0.0-beta3.jar) the terminal remains open (I mean the cmd is running) until I press ctl + X. Is this the required behaviour?

Yes. That means the server selenium is waiting to serve any request we are going to do through codeception. 

> 2 ) When I run the 2nd cmd (./vendor/bin/codecept run) a new chrome window opens (I guess it it testing) and then closes. Is this the required behaviour? Here is a screenshot:

Yes. Actually when it opens up, you should  see in real time one by one steps followed [here](https://github.com/rdok/company-web-app/blob/master/tests/acceptance/sample-work.feature) Only the mouse you cannot see. 

> 3) Here are the results I get. Is this the required behaviour?

Yes. See step 2 link for detailed info.

**Pull request merged**
